# THIS FILE IS EXCLUSIVELY MAINTAINED by the project aedev.project_tpls v0.3.79
""" setup of aedev namespace package portion project_manager: maintain Python projects locally and remotely. """
import sys
# noinspection PyUnresolvedReferences
import pathlib
# noinspection PyUnresolvedReferences
import setuptools


print("SetUp " + __name__ + ": " + sys.executable + str(sys.argv) + f" {sys.path=}")

setup_kwargs = {
    'author': 'AndiEcker',
    'author_email': 'aecker2@gmail.com',
    'classifiers': [
        'Development Status :: 3 - Alpha',
        'Natural Language :: English',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.12',
        'Topic :: Software Development :: Libraries :: Python Modules',
        'Typing :: Typed',
    ],
    'description': 'aedev namespace package portion project_manager: maintain Python projects locally and remotely',
    'entry_points': {
        'console_scripts': [
            'pjm = aedev.project_manager.__main__:main',
            'project-manager = aedev.project_manager.__main__:main',
        ],
    },
    'extras_require': {
        'dev': [
            'aedev_project_tpls==0.3.79',
            'aedev_aedev==0.3.33',
            'ae-parse-date==0.3.5',
            'ae_app_log==0.3.3',
            'ae_base==0.3.88',
            'ae_console==0.3.95',
            'ae_core==0.3.86',
            'ae_dynamicod==0.3.15',
            'ae_files==0.3.29',
            'ae_literal==0.3.35',
            'ae_managed_files==0.3.6',
            'ae_paths==0.3.46',
            'ae_pythonanywhere==0.3.6',
            'ae_shell==0.3.14',
            'ae_system==0.3.8',
            'ae_updater==0.3.19',
            'aedev_base==0.3.8',
            'aedev_commands==0.3.13',
            'aedev_project_vars==0.3.15',
            'anybadge==1.16.0',
            'argcomplete==3.6.3',
            'ast_serialize==0.5.0',
            'astroid==4.0.4',
            'certifi==2026.6.17',
            'cffi==2.0.0',
            'charset-normalizer==3.4.7',
            'click==8.4.1',
            'coverage==7.14.3',
            'cryptography==49.0.0',
            'dill==0.4.1',
            'flake8==7.3.0',
            'idna==3.18',
            'iniconfig==2.3.0',
            'isort==8.0.1',
            'librt==0.11.0',
            'mccabe==0.7.0',
            'mypy==2.1.0',
            'mypy_extensions==1.1.0',
            'packaging==26.2',
            'pathspec==1.1.1',
            'pillow==12.2.0',
            'pipx==1.15.0',
            'platformdirs==4.10.0',
            'pluggy==1.6.0',
            'pycodestyle==2.14.0',
            'pycparser==3.0',
            'pyflakes==3.4.0',
            'PyGithub==2.9.1',
            'Pygments==2.20.0',
            'pyjnius==1.7.0',
            'PyJWT==2.13.0',
            'pylint==4.0.6',
            'PyNaCl==1.6.2',
            'pytest==9.1.1',
            'pytest-cov==7.1.0',
            'python-gitlab==8.4.0',
            'requests==2.34.2',
            'requests-toolbelt==1.0.0',
            'setuptools==82.0.1',
            'tomlkit==0.15.0',
            'types-Pillow==10.2.0.20240822',
            'types-requests==2.33.0.20260518',
            'types-setuptools==82.0.0.20260518',
            'typing==3.7.4.3',
            'typing_extensions==4.15.0',
            'urllib3==2.7.0',
            'userpath==1.9.2',
            'anybadge==1.16.0',
            'flake8==7.3.0',
            'mypy==2.1.0',
            'pylint==4.0.6',
            'pytest==9.1.1',
            'pytest-cov==7.1.0',
            'typing==3.7.4.3',
            'types-setuptools==82.0.0.20260518',
        ],
        'docs': [],
        'tests': [
            'anybadge==1.16.0',
            'flake8==7.3.0',
            'mypy==2.1.0',
            'pylint==4.0.6',
            'pytest==9.1.1',
            'pytest-cov==7.1.0',
            'typing==3.7.4.3',
            'types-setuptools==82.0.0.20260518',
        ],
    },
    'install_requires': [
        'anybadge==1.16.0',
        'coverage==7.14.3',
        'flake8==7.3.0',
        'mypy==2.1.0',
        'packaging==26.2',
        'pillow==12.2.0',
        'types-Pillow==10.2.0.20240822',
        'PyGithub==2.9.1',
        'pylint==4.0.6',
        'pytest==9.1.1',
        'pytest-cov==7.1.0',
        'python-gitlab==8.4.0',
        'requests==2.34.2',
        'ae_base==0.3.88',
        'ae_system==0.3.8',
        'ae_paths==0.3.46',
        'ae_dynamicod==0.3.15',
        'ae_literal==0.3.35',
        'ae_updater==0.3.19',
        'ae_core==0.3.86',
        'ae_console==0.3.95',
        'ae_shell==0.3.14',
        'ae_managed_files==0.3.6',
        'ae_pythonanywhere==0.3.6',
        'aedev_base==0.3.8',
        'aedev_commands==0.3.13',
        'aedev_project_vars==0.3.15',
    ],
    'keywords': [
        'configuration',
        'development',
        'environment',
        'productivity',
    ],
    'license': 'GPL-3.0-or-later',
    'long_description': (pathlib.Path(__file__).parent / 'README.md').read_text(encoding='utf-8'),
    'long_description_content_type': 'text/markdown',
    'name': 'aedev_project_manager',
    'package_data': {
        '': [],
    },
    'packages': [
        'aedev.project_manager',
    ],
    'project_urls': {
        'Bug Tracker': 'https://gitlab.com/aedev-group/aedev_project_manager/-/issues',
        'Documentation': 'https://aedev.readthedocs.io/en/latest/_autosummary/aedev.project_manager.html',
        'Repository': 'https://gitlab.com/aedev-group/aedev_project_manager',
        'Source': 'https://aedev.readthedocs.io/en/latest/_modules/aedev/project_manager.html',
    },
    'python_requires': '>=3.12',
    'url': 'https://gitlab.com/aedev-group/aedev_project_manager',
    'version': '0.3.29',
    'zip_safe': True,
}

if __name__ == "__main__":
    setuptools.setup(**setup_kwargs)
    pass
